"""empty message

Revision ID: e94ac8df2859
Revises:
Create Date: 2020-06-12 19:32:37.816546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e94ac8df2859"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "chefs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("shop_link", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("instruction", sa.String(length=2048), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "cookbooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("chef_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["chef_id"], ["chefs.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "recipe_category_association",
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"],),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"],),
    )
    op.create_table(
        "recipe_product_association",
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"],),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"],),
    )
    op.create_table(
        "cookbook_recipe_association",
        sa.Column("cookbook_id", sa.Integer(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["cookbook_id"], ["cookbooks.id"],),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"],),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cookbook_recipe_association")
    op.drop_table("recipe_product_association")
    op.drop_table("recipe_category_association")
    op.drop_table("cookbooks")
    op.drop_table("recipes")
    op.drop_table("products")
    op.drop_table("chefs")
    op.drop_table("categories")
    # ### end Alembic commands ###
